version: '3.7'

services:

  db:
    image: postgres:10.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

  cache:
    image: redis:5.0.4-alpine3.9
    restart: always
    command: --maxmemory 200mb --maxmemory-policy allkeys-lru

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: ${DATABASE_URL}
    ports:
      - 127.0.0.1:8000:80
    depends_on:
      - db
      - cache
    volumes:
      - web-data:/app/var

  dotnet:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    entrypoint: dotnet
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: ${DATABASE_URL}
    volumes:
      - ./:/app


volumes:
  db-data:
  web-data:
  built-static:
